name: Deploy

on:
  push:
    tags:
      - "backend@*"
      - "frontend@*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
            go-version: '1.23'
      - name: Build Go
        run: make
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile_birthday
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/discord-birthday-bot:latest
      - name: Trigger Coolify Deploy
        run: |
         curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
