name: release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
            go-version: '1.23'

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          publish: make

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
