name: tags

on:
  push:
    tags:
      - "*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
            go-version: '1.23'
      - name: Build Go
        run: make

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile_birthday
          push: true
          tags: |
            "${{ secrets.DOCKERHUB_USERNAME }}/discord-birthday-bot:latest"
            "${{ secrets.DOCKERHUB_USERNAME }}/discord-birthday-bot:${{ github.ref_name }}"

      - name: Deploy to Coolify
        run: |
         curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'

  notes:
    runs-on: ubuntu-latest
    needs: [deploy]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract changelog
        run: |
          current_tag="${{ github.ref_name }}"

          previous_tag="$(git describe --tags --abbrev=0 HEAD^)"

          changelog="$(git diff --no-color --unified=0 \
           $previous_tag $current_tag -- CHANGELOG.md \
           --diff-filter=A | grep '^[+]' | sed '1d; s/^+//')"

          echo "$changelog" > changelog.txt

      - name: Generate release notes
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          body_path: changelog.txt

  notify:
    runs-on: ubuntu-latest
    needs: [notes]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Notify Discord
        run: |
          current_tag="${{ github.ref_name }}"

          previous_tag="$(git describe --tags --abbrev=0 HEAD^)"

          changelog="$(git diff --no-color --unified=0 \
           $previous_tag $current_tag -- CHANGELOG.md \
           --diff-filter=A | grep '^[+]' | sed '1d; s/^+//')"

          changelog="$changelog\n\nFull diff at https://github.com/Guergeiro/discord-bots/releases/tag/$current_tag"

          changelog_escaped=$(echo "$changelog" | sed ':a;N;$!ba;s/\n/\\n/g')

          json_payload="{\"content\": \"$changelog_escaped\"}"

          curl -H "Content-Type: application/json" -d "$json_payload" ${{ secrets.DISCORD_WEBHOOK_URL }}
